# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VM <- function(viewshed, dsm, slp, asp, viewpt, h, resolution) {
    .Call('_viewscape_VM', PACKAGE = 'viewscape', viewshed, dsm, slp, asp, viewpt, h, resolution)
}

dsm_to_pano <- function(dsm, vpt_x, vpt_y, vpt_z, pano_height = 256L, pano_width = 512L, ares = 0.0174533, step_size = 0.5, max_dist = 500.0, sky_value = -1.0, sky_threshold = 3.0, orientation = 0.0) {
    .Call('_viewscape_dsm_to_pano', PACKAGE = 'viewscape', dsm, vpt_x, vpt_y, vpt_z, pano_height, pano_width, ares, step_size, max_dist, sky_value, sky_threshold, orientation)
}

get_depths <- function(px, py, x, y, num) {
    .Call('_viewscape_get_depths', PACKAGE = 'viewscape', px, py, x, y, num)
}

sectorMask <- function(viewshed, viewpt, fov) {
    .Call('_viewscape_sectorMask', PACKAGE = 'viewscape', viewshed, viewpt, fov)
}

reference <- function(viewpoint, dsm, h, max_dis, refraction_factor) {
    .Call('_viewscape_reference', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis, refraction_factor)
}

LOS <- function(viewpoint, dsm, h, max_dis, refraction_factor) {
    .Call('_viewscape_LOS', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis, refraction_factor)
}

